version: '3'
services:
  app:
    build:
      context: .
    working_dir: /deploy/app
    volumes:
      - './app/:/deploy/app/'
    depends_on:
      - redis
    networks:
      - web_nw
  nginx:
    image: "nginx:mainline"
    volumes:
      - $PWD/conf.d:/etc/nginx/conf.d
      - $PWD/docs/build:/var/www/html/static
    environment:
      - net.ipv6.conf.all.forwarding=1 
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - web_nw
  redis:
    image: redis:5.0
    networks:
      - web_nw
  rq-scheduler:
    build: .
    command: "rqscheduler --host ${REDIS_HOST:-redis} -i 5 & rq worker --url redis://redis:6379 pollunator_subscribers"
    working_dir: /deploy/app
    depends_on:
      - app
    volumes:
      - './app/:/deploy/app/'
    networks:
      - web_nw
      
networks:
  web_nw: